### ISSUE TITLE
OSF2R::readOSF → error:1407742E:SSL (?)

### ISSUE THREAD

**Issue by RemPsyc** [SachaEpskamp/OSF2R#1]
Hi, after successfully installing your package, remotes::install_github("SachaEpskamp/OSF2R"), when I call the example:

`RPPmaster <- readOSF("5wup8", sheetName = "MASTER", startRow = 5, header = TRUE, redOSF, stringsAsFactors = FALSE)`

(or my own examples), I get the following error:

```
Error in function (type, msg, asError = TRUE)  : 
  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

I don't see an obvious way to fix this from my end. Is there?

**Comment by SachaEpskamp** [comment]
This package isn't really maintained or supported anymore, sorry.
